export const profiles = [
  { 
    id: '0',
    name: "Victor",
    level: 1,
    imageUrl: "https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg",
    languages: ["Chinese", "English"],
    hourlyRate: 5,
    dayRate: 50,
    age: 25,
    gender: "male",
    nationality: "Singaporean",
    description: "Walk with me around the beautiful streets of Singapore. I'll will show you how things are done here! Plus, first round of durians is on me!",
    overview: "",
    knowledge: ["Food", "Drinks"],
    vehicle: "Ferrari",
    vehicleFee: 20, 
    review: 4.5,
    reviewCount: 10,
    responseRate: "80%",
    responseTime: "5 minutes",
    place: "Bukit Panjang"
  },
  { 
    id: '1',
    name: "Amily",
    level: 10,
    imageUrl: "https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg",
    languages: ["English", "Malay"],
    hourlyRate: 5,
    dayRate: 70,
    age: 45,
    gender: "female",
    nationality: "Malaysian",
    description: "Chop me",
    overview: "",
    knowledge: ["Food", "Drinks"],
    vehicle: "Ferrari",
    vehicleFee: 20, 
    review: 4.5,
    reviewCount: 1,
    responseRate: "80%",
    responseTime: "5 minutes",
    place: "Bukit Panjang"
  },
  { 
    id: '2',
    name: "Bagar",
    level: 20,
    imageUrl: "https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg",
    languages: ["Chinese"],
    hourlyRate: 5,
    dayRate: 30,
    age: 35,
    gender: "male",
    nationality: "Chinese",
    description: "Chop me",
    overview: "",
    knowledge: ["Nothing"],
    vehicle: null,
    vehicleFee: null,
    review: 1.5,
    reviewCount: 10,
    responseRate: "50%",
    responseTime: "50 days",
    place: "ChinaTown"
  },
  { 
    id: '3',
    name: "Khan",
    level: 20,
    imageUrl: "https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg",
    languages: ["Chinese", "Russian"],
    hourlyRate: 39,
    dayRate: 100,
    age: 25,
    gender: "male",
    nationality: "Malaysian",
    description: "Chop me",
    overview: "",
    knowledge: ["Nothing"],
    vehicle: 30,
    vehicleFee: null,
    review: 3.5,
    reviewCount: 10,
    responseRate: "50%",
    responseTime: "50 days",
    place: "Ipoh"
  },
  { 
    id: '4',
    name: "Mint",
    level: 100,
    imageUrl: "https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg",
    languages: ["Chinese"],
    hourlyRate: 5,
    dayRate: 30,
    age: 45,
    gender: "femail",
    nationality: "Korean",
    description: "Chop me",
    overview: "",
    knowledge: ["Nothing"],
    vehicle: 100,
    vehicleFee: null,
    review: 1.5,
    reviewCount: 10,
    responseRate: "70%",
    responseTime: "20 days",
    place: "Singapore"
  },
  { 
    id: '5',
    name: "Hon",
    level: 2,
    imageUrl: "https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg",
    id: '0',languages: ["Vietnamese"],
    hourlyRate: 5,
    dayRate: 30,
    age: 25,
    gender: "male",
    nationality: "Mexican",
    description: "Chop me",
    overview: "",
    knowledge: ["Nothing"],
    vehicle: null,
    vehicleFee: null,
    review: 1.5,
    reviewCount: 10,
    responseRate: "20%",
    responseTime: "100 days",
    place: "Vietnam"
  }
]